type: m
# manager:
#   address: 1.1.1.1:6002
#   password: '123456'
plugins:
  flowSaver:
    use: true
  user:
    use: true
  account:
    use: true
  email:
    use: true
    type: 'smtp'
    username: 'username'
    password: 'password'
    host: 'smtp.your-email.com'
  webgui:
    use: true
    host: '0.0.0.0'
    port: '8080'
    site: 'http://yourwebsite.com'
    # icon: 'icon.png'
    # skin: 'default'
    # googleAnalytics: 'UA-xxxxxxxx-x'
db: 'webgui.sqlite'
# 从 0.30 开始需要配置 redis
redis:
  host: 'redis'
  port: 6379
  password: ''
  db: 0
